'use strict';

const categories = [
  { id: 1, name: 'あたため', icon: '🔥', sort_order: 1 },
  { id: 2, name: 'ゆで物・蒸し物', icon: '♨️', sort_order: 2 },
  { id: 3, name: '10分メニュー', icon: '⏱️', sort_order: 3 },
  { id: 4, name: '焼き物', icon: '🍳', sort_order: 4 },
  { id: 5, name: '揚げ物（油なし）', icon: '🍤', sort_order: 5 },
  { id: 6, name: '煮物', icon: '🍲', sort_order: 6 },
  { id: 7, name: 'ご飯・めん類', icon: '🍜', sort_order: 7 },
  { id: 8, name: 'ピザ・グラタン', icon: '🍕', sort_order: 8 },
  { id: 9, name: '自家製食品', icon: '🥩', sort_order: 9 },
  { id: 10, name: 'パン', icon: '🍞', sort_order: 10 },
  { id: 11, name: 'スイーツ', icon: '🍰', sort_order: 11 },
];

const autoMenus = [
  { id: 1,  menu_number: 1,  name: 'あたため',        heat_type: 'レンジ',          tank_setting: '空',   tray_position: 'テーブルプレート中央', description: '常温・冷蔵のごはん、お総菜のあたため' },
  { id: 2,  menu_number: 2,  name: '牛乳',            heat_type: 'レンジ',          tank_setting: '空',   tray_position: 'テーブルプレート中央', description: '牛乳のあたため（1〜4杯）' },
  { id: 3,  menu_number: 3,  name: '酒かん',          heat_type: 'レンジ',          tank_setting: '空',   tray_position: 'テーブルプレート中央', description: 'お酒のあたため（1〜4本）' },
  { id: 4,  menu_number: 4,  name: '解凍あたため',    heat_type: 'レンジ',          tank_setting: '空',   tray_position: 'テーブルプレート中央', description: '冷凍保存したごはん・お総菜のあたため' },
  { id: 5,  menu_number: 5,  name: 'コンビニ弁当',    heat_type: 'レンジ',          tank_setting: '空',   tray_position: 'テーブルプレート中央', description: 'コンビニ弁当のあたため' },
  { id: 6,  menu_number: 6,  name: '葉・果菜',        heat_type: 'レンジ',          tank_setting: '空',   tray_position: 'テーブルプレート', description: 'ほうれん草・ブロッコリーなど葉・果菜のゆで加熱' },
  { id: 7,  menu_number: 7,  name: '根菜',            heat_type: 'レンジ',          tank_setting: '空',   tray_position: 'テーブルプレート', description: 'じゃがいも・にんじんなど根菜の加熱' },
  { id: 8,  menu_number: 8,  name: 'スープパスタ',    heat_type: 'レンジ',          tank_setting: '空',   tray_position: 'テーブルプレート', description: 'スープパスタの調理' },
  { id: 9,  menu_number: 9,  name: '肉じゃが',        heat_type: 'レンジ',          tank_setting: '空',   tray_position: 'テーブルプレート', description: '肉じゃが・煮物の調理' },
  { id: 10, menu_number: 10, name: 'さけのホイル焼き', heat_type: 'オーブン',       tank_setting: '空',   tray_position: '黒皿・下段', description: 'さけなどのホイル焼き（約25分）' },
  { id: 11, menu_number: 11, name: 'ポークグリル',    heat_type: 'グリル',          tank_setting: '空',   tray_position: '黒皿・下段', description: '豚肉のグリル焼き（約20分）' },
  { id: 12, menu_number: 12, name: 'グラタン',        heat_type: 'オーブン',        tank_setting: '空',   tray_position: '黒皿・下段', description: 'グラタンの調理（約25分）' },
  { id: 13, menu_number: 13, name: 'ピザ',            heat_type: 'オーブン',        tank_setting: '空',   tray_position: '黒皿・下段', description: 'ピザの調理（予熱あり）' },
  { id: 14, menu_number: 14, name: '焼きそば',        heat_type: 'レンジ',          tank_setting: '空',   tray_position: 'テーブルプレート', description: '10分メニュー：焼きそば・炒め物（約6〜10分）' },
  { id: 15, menu_number: 15, name: '鶏の簡単蒸し',   heat_type: 'レンジ',          tank_setting: '空',   tray_position: 'テーブルプレート', description: '10分メニュー：鶏の簡単蒸し（約8分）' },
  { id: 16, menu_number: 16, name: 'マーボーなす',   heat_type: 'レンジ',          tank_setting: '空',   tray_position: 'テーブルプレート', description: '10分メニュー：マーボーなす・煮物（約10分）' },
  { id: 17, menu_number: 17, name: '解凍',            heat_type: 'スチーム',        tank_setting: '満水', tray_position: 'テーブルプレート', description: '肉・魚の解凍' },
  { id: 18, menu_number: 18, name: 'スチームあたため', heat_type: 'スチーム',       tank_setting: '満水', tray_position: 'テーブルプレート', description: 'ごはん・お総菜のスチームあたため' },
  { id: 19, menu_number: 19, name: '総菜パンあたため', heat_type: 'スチーム',       tank_setting: '満水', tray_position: 'テーブルプレート', description: '惣菜パン1〜3個のあたため' },
  { id: 20, menu_number: 20, name: '中華まんあたため', heat_type: 'スチーム',       tank_setting: '満水', tray_position: 'テーブルプレート', description: '中華まん1〜4個のあたため' },
  { id: 21, menu_number: 21, name: '天ぷらあたため',  heat_type: 'スチーム',        tank_setting: '満水', tray_position: '黒皿・上段', description: '天ぷら・揚げ物のあたため' },
  { id: 22, menu_number: 22, name: '焼き豚',          heat_type: 'スチームオーブン・グリル', tank_setting: '満水', tray_position: '黒皿・下段', description: '焼き豚（約59分）' },
  { id: 23, menu_number: 23, name: 'チーズトースト', heat_type: 'グリル',           tank_setting: '空',   tray_position: '黒皿・上段', description: 'チーズトーストの調理' },
  { id: 24, menu_number: 24, name: 'ケーキ',          heat_type: 'オーブン',        tank_setting: '空',   tray_position: '黒皿・下段', description: 'ケーキの調理' },
  { id: 25, menu_number: 25, name: 'クッキー',        heat_type: 'オーブン',        tank_setting: '空',   tray_position: '黒皿・下段', description: 'クッキーの調理' },
  { id: 26, menu_number: 26, name: '簡単パン',        heat_type: 'スチームオーブン', tank_setting: '満水', tray_position: '黒皿・下段', description: '手作りパンの発酵・焼き' },
  { id: 27, menu_number: 27, name: 'フランスパン',    heat_type: 'スチームオーブン', tank_setting: '満水', tray_position: '黒皿・下段', description: 'フランスパンの発酵・焼き' },
  { id: 28, menu_number: 28, name: 'シフォンケーキ', heat_type: 'オーブン',         tank_setting: '空',   tray_position: '黒皿・下段', description: 'シフォンケーキの調理' },
  { id: 29, menu_number: 29, name: 'カスタードプリン', heat_type: 'スチーム',       tank_setting: '満水', tray_position: 'テーブルプレート', description: 'プリンのスチーム調理' },
  { id: 30, menu_number: 30, name: '茶わん蒸し',      heat_type: 'スチーム',        tank_setting: '満水', tray_position: 'テーブルプレート', description: '茶わん蒸しのスチーム調理' },
  { id: 31, menu_number: 31, name: '焼きいも',        heat_type: 'スチームオーブン', tank_setting: '満水', tray_position: '黒皿・下段', description: '焼きいも（約65分）' },
  { id: 32, menu_number: 32, name: '自家製食品',      heat_type: 'スチーム',        tank_setting: '満水', tray_position: '黒皿・上段', description: '手作りソーセージ・ポークハムなど' },
  { id: 33, menu_number: 33, name: 'ハンバーグ',      heat_type: '過熱水蒸気・グリル', tank_setting: '満水', tray_position: '黒皿・上段', description: 'ハンバーグ（仕上がり調節弱、約25分）' },
  { id: 34, menu_number: 34, name: '鶏のハーブ焼き', heat_type: '過熱水蒸気・グリル', tank_setting: '満水', tray_position: '黒皿・上段', description: '鶏のハーブ焼き（約29分）' },
  { id: 35, menu_number: 35, name: '塩ざけ',          heat_type: '過熱水蒸気・グリル', tank_setting: '満水', tray_position: '黒皿・上段', description: '魚の焼き物（仕上がり調節弱、約19分）' },
  { id: 36, menu_number: 36, name: '焼き野菜',        heat_type: '過熱水蒸気・グリル', tank_setting: '満水', tray_position: '黒皿・上段', description: '焼き野菜（約23分）' },
  { id: 37, menu_number: 37, name: '鶏のから揚げ',   heat_type: '過熱水蒸気・グリル', tank_setting: '満水', tray_position: '黒皿・上段', description: '油なし鶏のから揚げ（約24分）' },
  { id: 38, menu_number: 38, name: 'オーブン天ぷら', heat_type: '過熱水蒸気・グリル', tank_setting: '満水', tray_position: '黒皿・上段', description: '油なしオーブン天ぷら（約28分）' },
  { id: 39, menu_number: 39, name: 'ヒレカツ',        heat_type: '過熱水蒸気・グリル', tank_setting: '満水', tray_position: '黒皿・上段', description: '油なしヒレカツ（約25分）' },
  { id: 40, menu_number: 40, name: 'とんカツ',        heat_type: '過熱水蒸気・グリル', tank_setting: '満水', tray_position: '黒皿・上段', description: '油なしとんカツ（約22分）' },
  { id: 41, menu_number: 41, name: 'チキンカツ',      heat_type: '過熱水蒸気・グリル', tank_setting: '満水', tray_position: '黒皿・上段', description: '油なしチキンカツ（約22分）' },
  { id: 42, menu_number: 42, name: 'えびフライ',      heat_type: '過熱水蒸気・グリル', tank_setting: '満水', tray_position: '黒皿・上段', description: '油なしえびフライ（約22分）' },
];

const recipes = [
  // ===== あたため =====
  {
    id: 1, title: '牛乳のあたため', subtitle: '', category_id: 1, auto_menu_id: 2,
    servings: '1〜4杯', heating_time: '1杯（200mL）約1分38秒',
    heating_method: 'レンジ・飲み物デイリー 2牛乳', temperature: '',
    tips: 'マグカップやコップに入れて、杯数をセットして加熱する。',
    notes: '',
    ingredients: [
      { group_label: '', name: '牛乳', amount: '200mL（1杯分）' },
    ],
    steps: [
      '牛乳をマグカップまたはコップに入れる。',
      '飲み物・デイリー 2牛乳 で杯数をセットして加熱する。',
    ],
  },
  {
    id: 2, title: 'お酒のあたため（酒かん）', subtitle: '', category_id: 1, auto_menu_id: 3,
    servings: '1〜4本', heating_time: '1本（180mL）約1分',
    heating_method: 'レンジ・飲み物デイリー 3酒かん', temperature: '',
    tips: '徳利で加熱するときは、くびれた部分より1cmほど下くらいまで入れる。びん詰めのお酒は、栓を抜いてから加熱する。',
    notes: '',
    ingredients: [
      { group_label: '', name: '日本酒', amount: '180mL（1本分）' },
    ],
    steps: [
      'お酒をコップまたは徳利に入れる。',
      '飲み物・デイリー 3酒かん で本数をセットして加熱する。',
    ],
  },
  {
    id: 3, title: 'ごはんのスチームあたため', subtitle: '', category_id: 1, auto_menu_id: 18,
    servings: '1人分', heating_time: '1杯（約150g）約2分',
    heating_method: 'スチーム調理 18スチームあたため', temperature: '',
    tips: 'ラップなどのおおいをしないで加熱する。冷凍のごはんは4解凍あたためを使う。',
    notes: '給水タンクに満水ラインまで水を入れてセットする。',
    ingredients: [
      { group_label: '', name: 'ごはん', amount: '約150g（1杯分）' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      'ラップなどのおおいをしないでスチーム調理 18スチームあたためで加熱する。',
    ],
  },
  // ===== ゆで物・蒸し物 =====
  {
    id: 4, title: 'ほうれん草のおひたし', subtitle: '', category_id: 2, auto_menu_id: 6,
    servings: '4人分', heating_time: '約2分',
    heating_method: 'レンジ・飲み物デイリー 6葉・果菜', temperature: '',
    tips: 'ほうれん草などは、加熱後すぐに水に取る。水けを切らずにラップでぴったり包み、テーブルプレートに直接のせて加熱する。',
    notes: '',
    ingredients: [
      { group_label: '', name: 'ほうれん草', amount: '200g' },
      { group_label: '', name: '糸がつお', amount: '適量' },
      { group_label: '', name: 'しょうゆ', amount: '適量' },
    ],
    steps: [
      'ほうれん草は洗ってかるく水けを切り、根元の太い物は十文字に切り込みを入れる。',
      '葉先と根元を交互にしてラップでピッタリ包む。',
      '飲み物・デイリー 6葉・果菜で加熱し、水に取ってアク抜きと色止めをする。',
      '器に盛り、糸がつおをのせ、しょうゆを添える。',
    ],
  },
  {
    id: 5, title: 'イタリアンサラダ', subtitle: '', category_id: 2, auto_menu_id: 6,
    servings: '4人分', heating_time: 'さやいんげん約2分、じゃがいも約8分',
    heating_method: 'レンジ・6葉・果菜 / 7根菜', temperature: '',
    tips: '材料に合ったアク抜きをする。',
    notes: '',
    ingredients: [
      { group_label: '', name: 'さやいんげん', amount: '200g' },
      { group_label: '', name: 'じゃがいも', amount: '大2個（約400g）' },
      { group_label: '', name: 'サラミソーセージ（薄切り）', amount: '12枚' },
      { group_label: '', name: 'プロセスチーズ（1cm角切り）', amount: '60g' },
      { group_label: '', name: 'スタッフドオリーブ（薄切り）', amount: '12個' },
      { group_label: '', name: 'アンチョビー（みじん切り）', amount: '8枚' },
      { group_label: 'A', name: '玉ねぎ（みじん切り）', amount: '1/4個（約50g）' },
      { group_label: 'A', name: 'パセリ（みじん切り）', amount: '大さじ1' },
      { group_label: 'A', name: 'レモン汁', amount: '大さじ1' },
      { group_label: 'A', name: 'こしょう', amount: '少々' },
      { group_label: '', name: 'オリーブ油', amount: 'カップ1/2' },
      { group_label: '', name: 'レモン（くし形切り）', amount: '適量' },
    ],
    steps: [
      'さやいんげんはへたを取り、長い物は半分に切ってラップで包み 6葉・果菜で加熱してざるに取る。',
      'じゃがいもはきれいに洗い、皮ごとラップで包む。7根菜で加熱し、熱いうちに皮をむき、厚さ1cmの半月切りにする。',
      'ボウルにAを入れ、かき混ぜながらオリーブ油を加えてドレッシングを作る。',
      '材料すべてを3のドレッシングであえて皿に盛り、レモンを飾る。',
    ],
  },
  // ===== 10分メニュー =====
  {
    id: 6, title: '焼きそば', subtitle: '', category_id: 3, auto_menu_id: 14,
    servings: '1〜2人分', heating_time: '約6分',
    heating_method: 'レンジ・10分メニュー 14焼きそば', temperature: '',
    tips: '少し深めの陶磁器や耐熱皿を使う。ラップは耐熱温度が140℃以上の物を使う。',
    notes: '',
    ingredients: [
      { group_label: '', name: '焼きそば用めん（ソース付き）', amount: '1袋' },
      { group_label: '', name: '野菜ミックス（約250gの物）', amount: '1袋' },
      { group_label: '', name: '豚薄切り肉（ひとくち大に切る）', amount: '50g' },
      { group_label: '', name: '塩、こしょう', amount: '各少々' },
    ],
    steps: [
      '深めの皿にめん、豚肉、野菜ミックスの半量を順に入れ、ソース、塩、こしょうをかけ、残りの野菜をのせてラップをする。',
      '10分メニュー 14焼きそばで加熱し、かき混ぜる。',
    ],
  },
  {
    id: 7, title: 'チンジャオロウスー', subtitle: '牛肉とピーマンの細切りいため', category_id: 3, auto_menu_id: 14,
    servings: '2〜3人分', heating_time: '約6分',
    heating_method: 'レンジ・10分メニュー 14焼きそば', temperature: '',
    tips: '牛もも肉のかわりに豚肉を使ってもよい。切った野菜は、しっかり水切りしておくとよい。',
    notes: '',
    ingredients: [
      { group_label: '', name: '牛もも肉（細切り）', amount: '150g' },
      { group_label: '', name: 'ピーマン（種を取り、タテに細切り）', amount: '4個' },
      { group_label: 'A', name: 'たけのこ水煮（細切り）', amount: '50g' },
      { group_label: 'A', name: 'しょうゆ', amount: '小さじ1' },
      { group_label: 'A', name: 'オイスターソース', amount: '大さじ1' },
      { group_label: 'B', name: '酒', amount: '大さじ1' },
      { group_label: 'B', name: '砂糖', amount: '小さじ1' },
      { group_label: 'B', name: '鶏がらスープの素（顆粒）', amount: '小さじ1' },
      { group_label: 'B', name: '片栗粉', amount: '小さじ1' },
    ],
    steps: [
      '牛もも肉にかるく塩、こしょう（各少々・分量外）をし、片栗粉小さじ1（分量外）をふり、よくまぶしておく。',
      '深めの皿に1とA、合わせたBを入れてかるく混ぜ、かるくラップをする。',
      '10分メニュー 14焼きそばで加熱し、かき混ぜる。',
    ],
  },
  {
    id: 8, title: 'ゴーヤーチャンプル', subtitle: '', category_id: 3, auto_menu_id: 14,
    servings: '2〜3人分', heating_time: '約6分（下ごしらえ レンジ600W 約1分50秒＋40秒〜1分）',
    heating_method: 'レンジ・10分メニュー 14焼きそば', temperature: '',
    tips: 'ゴーヤーは塩もみして苦みを抜く。豆腐は事前にレンジで水切りする。',
    notes: '',
    ingredients: [
      { group_label: '', name: 'ゴーヤー（にがうり）', amount: '1本（約200g）' },
      { group_label: '', name: '赤パプリカ（種を取り、タテに細切り）', amount: '1/2個（約50g）' },
      { group_label: '', name: '豚バラ肉（薄切り、ひとくち大に切る）', amount: '50g' },
      { group_label: '', name: '木綿豆腐', amount: '1/2丁（約150g）' },
      { group_label: '', name: '卵', amount: '1個' },
      { group_label: 'A', name: 'しょうゆ', amount: '小さじ1' },
      { group_label: 'A', name: '塩', amount: '小さじ1/3' },
      { group_label: 'A', name: '酒', amount: '大さじ1' },
      { group_label: 'A', name: '砂糖', amount: '小さじ1' },
      { group_label: 'A', name: '鶏がらスープの素（顆粒）', amount: '小さじ1' },
      { group_label: 'A', name: '片栗粉', amount: '小さじ1/2' },
    ],
    steps: [
      'ゴーヤーはタテ半分に切り、種とワタを取り5mm幅の薄切りにして、かるく塩（分量外）をふり、しんなりするまでしばらくおいた後、もみ洗いし、水けを切っておく。',
      '木綿豆腐は皿にのせ、おおいをしないでレンジ600W 約1分50秒で加熱し、ふきんなどで水けをふき取り水切りしておく。',
      '卵は耐熱コップに割り入れ、はしでよくかき混ぜ、レンジ500W 40秒〜1分で加熱し、いり卵にしておく。',
      '深めの皿に1と手でくずした2、赤パプリカ、豚肉、合わせたAを入れてかるく混ぜ、かるくラップをする。',
      '10分メニュー 14焼きそばで加熱し、最後に3を加えてかき混ぜる。',
    ],
  },
  {
    id: 9, title: '鶏の簡単蒸し', subtitle: '', category_id: 3, auto_menu_id: 15,
    servings: '1枚分', heating_time: '約8分',
    heating_method: 'レンジ・10分メニュー 15鶏の簡単蒸し', temperature: '',
    tips: '肉の厚さが1cm以上あるところに1/3以上、等間隔に切り目を入れる。深さ3〜4cmの耐熱平皿を使用する。',
    notes: '',
    ingredients: [
      { group_label: '', name: '鶏むね肉（皮なし、1枚約200gの物）', amount: '1枚' },
      { group_label: '', name: '酒', amount: '大さじ1' },
      { group_label: '', name: '塩', amount: '少々' },
      { group_label: '', name: 'しょうが汁', amount: '小さじ1' },
      { group_label: '', name: '白菜（ひとくち大に切る）', amount: '100g' },
      { group_label: '香味ソース', name: '長ねぎ（あらめのみじん切り）', amount: '1/2本分' },
      { group_label: '香味ソース', name: 'しょうが（みじん切り）', amount: '1かけ' },
      { group_label: '香味ソース', name: 'しょうゆ', amount: '大さじ3' },
      { group_label: '香味ソース', name: '酢', amount: '大さじ3' },
      { group_label: '香味ソース', name: 'ごま油', amount: '大さじ1/2' },
      { group_label: '香味ソース', name: 'ラー油', amount: '大さじ1/2' },
    ],
    steps: [
      '鶏肉は厚みのあるところに切り目を入れ、塩をして酒としょうが汁をふりかける。',
      '深さのある平皿に1を置き、まわりに白菜を広げる。かるくラップをして10分メニュー 15鶏の簡単蒸しで加熱する。',
      '加熱終了後、あら熱を取ってから切り分け、お好みでソースをかける。',
      '香味ソースは容器に材料を入れよく混ぜる。',
    ],
  },
  {
    id: 10, title: '鶏ハムの簡単蒸し', subtitle: '', category_id: 3, auto_menu_id: 15,
    servings: '1枚分', heating_time: '約8分',
    heating_method: 'レンジ・10分メニュー 15鶏の簡単蒸し', temperature: '',
    tips: '冷蔵室などで完全に冷ますと、よりしっとりとした食感になる。',
    notes: '前日から仕込む（冷蔵室に1日おく）。',
    ingredients: [
      { group_label: '', name: '鶏むね肉（皮なし、1枚約200gの物）', amount: '1枚' },
      { group_label: 'A', name: '白ワイン', amount: '大さじ1' },
      { group_label: 'A', name: 'ハチミツ', amount: '小さじ2' },
      { group_label: 'A', name: '塩', amount: '小さじ1' },
      { group_label: 'A', name: 'こしょう', amount: '少々' },
      { group_label: '', name: '白菜（ひとくち大に切る）', amount: '100g' },
    ],
    steps: [
      '鶏肉はポリ袋（市販）に入れて、Aを加えてもみ込んで冷蔵室に1日おく。厚みのあるところに切り目を入れる。',
      '深さのある平皿に1を置き、まわりに白菜を広げる。かるくラップをして、10分メニュー 15鶏の簡単蒸しで加熱する。',
      '加熱終了後、あら熱を取ってから切り分ける。',
    ],
  },
  {
    id: 11, title: 'マーボーなす', subtitle: '', category_id: 3, auto_menu_id: 16,
    servings: '2〜3人分', heating_time: '約10分',
    heating_method: 'レンジ・10分メニュー 16マーボーなす', temperature: '',
    tips: '容器は直径約25cm（内径約22.5cm）、深さ約10cmの広口の耐熱ガラスボウルが適している。落としぶたをする（オーブンシートを丸形に切り十文字の切り目を入れる）。',
    notes: '',
    ingredients: [
      { group_label: '', name: 'なす', amount: '3本（約300g）' },
      { group_label: '', name: '豚ひき肉', amount: '100g' },
      { group_label: 'A', name: '長ねぎ（みじん切り）', amount: '大さじ2' },
      { group_label: 'A', name: 'にんにく（みじん切り）', amount: '1片' },
      { group_label: 'A', name: 'しょうが（みじん切り）', amount: '1/2かけ' },
      { group_label: 'A', name: '豆板醤', amount: '小さじ1' },
      { group_label: 'A', name: '甜面醤（テンメンジャン）', amount: '小さじ2' },
      { group_label: 'A', name: '水', amount: 'カップ3/4' },
      { group_label: 'A', name: '鶏がらスープの素（顆粒）', amount: '小さじ1' },
      { group_label: 'A', name: 'しょうゆ', amount: '大さじ1' },
      { group_label: 'A', name: '砂糖', amount: '小さじ1' },
      { group_label: 'A', name: 'ごま油', amount: '小さじ1/2' },
      { group_label: 'A', name: '塩', amount: '少々' },
      { group_label: 'B', name: '片栗粉', amount: '大さじ1' },
      { group_label: 'B', name: '水', amount: '大さじ1' },
    ],
    steps: [
      'なすはへたを切り取ってタテに4等分し、水にさらしておく。',
      '大きくて深めの耐熱ガラスボウルに水けを切った1と豚ひき肉、Aの材料を入れよく混ぜる。',
      '2にオーブンシートで落としぶたをし、かるくラップをして10分メニュー 16マーボーなすで加熱する。',
      '加熱後、熱いうちに合わせたBを加えてよくかき混ぜ、とろみをつける。',
    ],
  },
  {
    id: 12, title: '肉豆腐', subtitle: '', category_id: 3, auto_menu_id: 16,
    servings: '2〜3人分', heating_time: '約10分',
    heating_method: 'レンジ・10分メニュー 16マーボーなす', temperature: '',
    tips: '材料は大きさをなるべくそろえて均一に加熱されるようにする。落としぶたをする。',
    notes: '',
    ingredients: [
      { group_label: '', name: '牛バラ肉（薄切り）', amount: '200g' },
      { group_label: '', name: '木綿豆腐', amount: '2/3丁（約200g）' },
      { group_label: '', name: '長ねぎ', amount: '1本（約70g）' },
      { group_label: '', name: 'えのきだけ', amount: '100g' },
      { group_label: '', name: '白滝', amount: '100g' },
      { group_label: 'A', name: '砂糖', amount: '大さじ2' },
      { group_label: 'A', name: 'しょうゆ', amount: '大さじ3' },
      { group_label: 'A', name: '酒', amount: '大さじ1' },
      { group_label: 'A', name: 'だし汁', amount: 'カップ1/2' },
    ],
    steps: [
      '豆腐は水切りをして9等分する。',
      'えのきだけは石づきを切ってほぐし、長ねぎは5mm幅のナナメ切りにする。',
      '大きくて深めの耐熱ガラスボウルに牛肉と白滝を離して材料をすべて並べて入れ、合わせたAをかけオーブンシートで落としぶたをし、かるくラップをして10分メニュー 16マーボーなすで加熱してかき混ぜる。',
    ],
  },
  // ===== 焼き物 =====
  {
    id: 13, title: 'さけのホイル焼き', subtitle: '', category_id: 4, auto_menu_id: 10,
    servings: '4枚分', heating_time: '約25分',
    heating_method: 'オーブン・飲み物デイリー 10さけのホイル焼き', temperature: '',
    tips: '1回に焼ける分量は4個まで。ホイルは黒皿の中央に寄せて並べる。',
    notes: '',
    ingredients: [
      { group_label: '', name: '生ざけの切り身（1切れ約80gの物）', amount: '4切れ' },
      { group_label: '', name: '大正えび（殻をむき背わたを取る）', amount: '4尾' },
      { group_label: '', name: '生しいたけ（石づきを取る）', amount: '4枚' },
      { group_label: '', name: '玉ねぎ（薄切り）', amount: '1個（約200g）' },
      { group_label: '', name: 'レモン（薄切り）', amount: '4枚' },
      { group_label: '', name: 'バター（5mm角に切る）', amount: '40g' },
      { group_label: '', name: '塩、こしょう、レモン汁', amount: '各少々' },
    ],
    steps: [
      'さけは1切れを3等分に切り、かるく塩、こしょうをしてレモン汁をふりかけておく。',
      '25×25cmの大きさに切ったアルミホイル4枚に薄くバター（分量外）を塗る。',
      '2に玉ねぎを等分にのせ、1、えび、しいたけをそれぞれ入れ、塩、こしょうをしてレモン汁をふり、上にレモンをのせ、バターを等分して上に散らす。',
      'アルミホイルの口を閉じて黒皿に並べ、下段に入れ 飲み物・デイリー 10さけのホイル焼きで焼く。',
    ],
  },
  {
    id: 14, title: 'えびとほたてのホイル焼き', subtitle: '', category_id: 4, auto_menu_id: 10,
    servings: '4個分', heating_time: '約25分',
    heating_method: 'オーブン・飲み物デイリー 10さけのホイル焼き', temperature: '',
    tips: '黒皿の中央に寄せて並べる。',
    notes: '',
    ingredients: [
      { group_label: '', name: '大正えび（殻をむき背わたを取る）', amount: '8尾' },
      { group_label: '', name: 'ほたて貝柱', amount: '8個' },
      { group_label: '', name: '生しいたけ、しめじなど好みのきのこ', amount: '合わせて280g' },
      { group_label: '', name: 'バター、酒、塩、こしょう', amount: '各少々' },
    ],
    steps: [
      '25×25cmの大きさに切ったアルミホイル4枚に薄くバター（分量外）を塗る。',
      '1にえび、ほたて、きのこを各々4等分してアルミホイルにのせ、バター、酒、塩、こしょうを加え、アルミホイルの口を閉じて黒皿に並べ、下段に入れ 飲み物・デイリー 10さけのホイル焼きで焼く。',
    ],
  },
  {
    id: 15, title: 'ポークグリル', subtitle: '', category_id: 4, auto_menu_id: 11,
    servings: '4枚分', heating_time: '約20分',
    heating_method: 'グリル・飲み物デイリー 11ポークグリル', temperature: '',
    tips: '1回に焼ける分量は2〜4枚。肉に含まれる脂の量によって焼き色がかわる。3段階の仕上がり調節で焼き加減を調節する。',
    notes: '',
    ingredients: [
      { group_label: '', name: '豚ロース肉（厚さ1cm、1枚約100gの物）', amount: '4枚' },
      { group_label: '', name: '酒', amount: '大さじ2' },
      { group_label: '', name: 'こしょう', amount: '少々' },
      { group_label: '赤ワインソース', name: '赤ワイン', amount: '大さじ4' },
      { group_label: '赤ワインソース', name: 'トマトケチャップ', amount: '大さじ1' },
      { group_label: '赤ワインソース', name: '塩、こしょう', amount: '各少々' },
    ],
    steps: [
      '豚ロース肉は筋切りをし、酒とこしょうでもみ込み30分おき、ペーパータオルで汁けをふき取る。',
      '黒皿に1を並べ、下段に入れ 飲み物・デイリー 11ポークグリルで焼き、赤ワインソースを添える。',
      '赤ワインソース：ポークグリルを加熱後の黒皿に残っている肉汁を深めの耐熱容器に入れ、赤ワイン、トマトケチャップ、塩、こしょうを合わせ、レンジ600W 約1分20秒、レンジ200W 約3分でリレー加熱して作る。',
    ],
  },
  {
    id: 16, title: '焼き豚', subtitle: '', category_id: 4, auto_menu_id: 22,
    servings: '3〜4人分', heating_time: '約59分',
    heating_method: 'スチームオーブン・グリル 22焼き豚', temperature: '',
    tips: '直径4〜6cmの物を使う。冷蔵室で半日以上つけ込む（前日から仕込む）。竹ぐしを刺して透明な肉汁が出れば焼き上がり。',
    notes: '給水タンクに満水ラインまで水を入れてセットする。',
    ingredients: [
      { group_label: '', name: '豚肩ロース肉（かたまり）', amount: '約500g' },
      { group_label: 'A', name: 'しょうが（みじん切り）', amount: '1かけ' },
      { group_label: 'A', name: '長ねぎ（みじん切り）', amount: '1/2本' },
      { group_label: 'A', name: 'しょうゆ、酒', amount: '各大さじ4' },
      { group_label: 'A', name: '砂糖、赤みそ', amount: '各大さじ1/2' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      '豚肉は木綿製のたこ糸でしばって形を整え、Aと一緒にポリ袋（市販）に入れ、冷蔵室で半日以上おく。',
      '黒皿にアルミホイルまたはオーブンシートを敷き、サラダ油（分量外）を塗り、汁けを切った2をのせ下段に入れ スチーム調理 22焼き豚で焼く。',
      'たこ糸を取って薄く切り、器に盛りつける。',
    ],
  },
  {
    id: 17, title: '焼きいも', subtitle: '', category_id: 4, auto_menu_id: 31,
    servings: '2〜4本', heating_time: '約65分',
    heating_method: 'スチームオーブン 31焼きいも', temperature: '',
    tips: '直径約4cmの物が適している。それ以上太い場合は1本を2等分か3等分にする。細いさつまいも（180g以下）や小さいさつまいも（130g以下）は仕上がり調節弱で加熱する。',
    notes: '給水タンクに満水ラインまで水を入れてセットする。',
    ingredients: [
      { group_label: '', name: 'さつまいも（1本約250gの物）', amount: '2〜4本' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      'さつまいもは皮にフォークで穴をあけるか包丁で切り目を入れてから、黒皿に並べて下段に入れ スチーム調理 31焼きいもで焼く。',
      '竹ぐしで刺してみて、通ればできあがり。',
    ],
  },
  {
    id: 18, title: 'ハンバーグ', subtitle: '', category_id: 4, auto_menu_id: 33,
    servings: '4個分', heating_time: '仕上がり調節弱で約25分',
    heating_method: '過熱水蒸気・グリル 33ハンバーグ（仕上がり調節弱）', temperature: '',
    tips: '1回に焼ける分量は2〜4個。生地の中央をくぼませると火の通りが良く、焼き上がりの中央のふくれを防ぐ。厚さは1.5〜2cmにする。',
    notes: '給水タンクに満水ラインまで水を入れてセットする。',
    ingredients: [
      { group_label: 'A', name: '玉ねぎ（みじん切り）', amount: '中1/2個（約100g）' },
      { group_label: 'A', name: 'バター', amount: '15g' },
      { group_label: '', name: '合びき肉', amount: '300g' },
      { group_label: '', name: 'パン粉', amount: 'カップ3/4（約30g）' },
      { group_label: '', name: '牛乳', amount: '大さじ3' },
      { group_label: '', name: '卵（溶きほぐす）', amount: '1個' },
      { group_label: '', name: '塩', amount: '小さじ1/2弱' },
      { group_label: '', name: 'こしょう、ナツメグ', amount: '各少々' },
      { group_label: 'ソース', name: 'トマトケチャップ、ウスターソース', amount: '各適量' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      'ボウルに材料を全部入れ、よく混ぜ合わせて4等分する。',
      '手にサラダ油（分量外）をつけ、2を片手に数回たたきつけて空気を抜き、厚さ1.5〜2cmの小判形にして中央をくぼませる。',
      '黒皿にアルミホイルまたはオーブンシートを敷き、3を並べて上段に入れ 過熱水蒸気 33ハンバーグ 仕上がり調節弱で焼く。',
    ],
  },
  {
    id: 19, title: 'ピーマンの肉詰め', subtitle: '', category_id: 4, auto_menu_id: 33,
    servings: '16個分（4人分）', heating_time: '約29分（下ごしらえ レンジ600W 約1分50秒）',
    heating_method: '過熱水蒸気・グリル 33ハンバーグ', temperature: '',
    tips: '黒皿の汚れが気になるときはオーブンシートを敷く。',
    notes: '給水タンクに満水ラインまで水を入れてセットする。',
    ingredients: [
      { group_label: '', name: 'ピーマン', amount: '8個' },
      { group_label: 'A', name: '玉ねぎ', amount: '大1/2個（約130g）' },
      { group_label: 'A', name: 'バター', amount: '大さじ1（約12g）' },
      { group_label: 'B', name: '豚ひき肉（または合びき肉）', amount: '260g' },
      { group_label: 'B', name: 'パン粉', amount: '20g' },
      { group_label: 'B', name: '卵（溶きほぐす）', amount: '大1個' },
      { group_label: 'B', name: '塩', amount: '小さじ1/2' },
      { group_label: 'B', name: 'こしょう', amount: '少々' },
      { group_label: '', name: '小麦粉（薄力粉）', amount: '適量' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      '耐熱容器にAを入れ レンジ600W 約1分50秒で加熱して、あら熱を取る。',
      'ピーマンはへたを残したままタテ2つ割りにして種を除き、水けを切って内側に小麦粉をふる。',
      'ボウルにBと2を入れ、よく混ぜ合わせて16等分し、3に詰める。',
      '黒皿に4を並べて上段に入れ 過熱水蒸気 33ハンバーグで焼く。',
    ],
  },
  {
    id: 20, title: '鶏のハーブ焼き', subtitle: '', category_id: 4, auto_menu_id: 34,
    servings: '4人分', heating_time: '約29分（下ごしらえ レンジ600W 約2分30秒）',
    heating_method: '過熱水蒸気・グリル 34鶏のハーブ焼き', temperature: '',
    tips: '1回に焼ける分量は1〜2枚分。加熱後、黒皿を取り出すときは脂や焼き汁に注意して傾けないように取り出す。',
    notes: '給水タンクに満水ラインまで水を入れてセットする。',
    ingredients: [
      { group_label: '', name: '鶏むね肉またはもも肉（皮つき）', amount: '2枚（約500g）' },
      { group_label: '', name: '塩、こしょう', amount: '各適量' },
      { group_label: 'A', name: 'タイム、ローズマリー、マジョラムなどのハーブ（生または乾燥品）', amount: '各少々' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      '鶏肉は、皮にフォークなどで穴を開け、厚みのあるところには切り目を入れてAをまぶす。',
      '2の皮を上にして黒皿の中央に寄せて並べ、上段に入れ、過熱水蒸気 34鶏のハーブ焼きで焼く。',
    ],
  },
  {
    id: 21, title: '塩ざけ', subtitle: '', category_id: 4, auto_menu_id: 35,
    servings: '4切れ分', heating_time: '仕上がり調節弱で約19分',
    heating_method: '過熱水蒸気・グリル 35塩ざけ（仕上がり調節弱）', temperature: '',
    tips: '1回に焼ける分量は切り身2〜4切れ（160〜400g）。1切れが70g以下のときはグリルで様子を見ながら焼く。黒皿の中央に寄せて並べる。',
    notes: '給水タンクに満水ラインまで水を入れてセットする。',
    ingredients: [
      { group_label: '', name: '塩ざけの切り身（1切れ約80gの物）', amount: '4切れ' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      '黒皿に、盛りつけたときに上になる方を上にして黒皿の中央に寄せて並べ、上段に入れ、過熱水蒸気 35塩ざけで焼く。',
    ],
  },
  {
    id: 22, title: 'さばのごま焼き', subtitle: '', category_id: 4, auto_menu_id: 35,
    servings: '8個分（2〜4人分）', heating_time: '仕上がり調節弱で約19分',
    heating_method: '過熱水蒸気・グリル 35塩ざけ（仕上がり調節弱）', temperature: '',
    tips: '',
    notes: '給水タンクに満水ラインまで水を入れてセットする。',
    ingredients: [
      { group_label: '', name: 'さばの切り身（3枚におろした物を4つに切る）', amount: '2枚（約300g）' },
      { group_label: 'A', name: 'しょうゆ', amount: '大さじ2' },
      { group_label: 'A', name: '酒', amount: '大さじ1' },
      { group_label: 'A', name: '砂糖', amount: '大さじ1/2' },
      { group_label: 'A', name: 'しょうが汁', amount: '小さじ1' },
      { group_label: '', name: '酒', amount: '大さじ1' },
      { group_label: '', name: '白ごま（あらくきざむ）', amount: '適量' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      'さばは水けをふき取り、合わせたAに15分以上つけて下味をつける。',
      '2の汁けをかるく切り、白ごまを全体にまぶす。',
      '黒皿に、3の盛りつけたときに上になる方を上にして黒皿の中央に寄せて並べ、上段に入れ、過熱水蒸気 35塩ざけ 仕上がり調節弱で焼き、仕上げに青のり粉（分量外）をふる。',
    ],
  },
  {
    id: 23, title: 'ぶりの照り焼き', subtitle: '', category_id: 4, auto_menu_id: 35,
    servings: '4切れ分', heating_time: '仕上がり調節弱で約19分',
    heating_method: '過熱水蒸気・グリル 35塩ざけ（仕上がり調節弱）', temperature: '',
    tips: '',
    notes: '給水タンクに満水ラインまで水を入れてセットする。30分〜1時間下味をつける。',
    ingredients: [
      { group_label: '', name: 'ぶり（1切れ約100gの物）', amount: '4切れ' },
      { group_label: 'A', name: 'しょうゆ', amount: 'カップ1/4' },
      { group_label: 'A', name: 'みりん', amount: 'カップ1/4' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      'ぶりは水けをふき取り、合わせたAに30分〜1時間つけて下味をつけ、ペーパータオルで汁けをかるく切る。',
      '黒皿に、2の盛りつけたときに上になる方を上にして黒皿の中央に寄せて並べ、上段に入れ、過熱水蒸気 35塩ざけ 仕上がり調節弱で焼く。',
    ],
  },
  {
    id: 24, title: '焼き野菜', subtitle: '', category_id: 4, auto_menu_id: 36,
    servings: '4人分', heating_time: '約23分',
    heating_method: '過熱水蒸気・グリル 36焼き野菜', temperature: '',
    tips: '1回に焼ける分量は表示の分量の0.8〜1.3倍量。黒皿の汚れが気になるときはオーブンシートを敷く。',
    notes: '給水タンクに満水ラインまで水を入れてセットする。',
    ingredients: [
      { group_label: '', name: 'ブロッコリー、カリフラワー、キャベツ、赤キャベツ、芽キャベツ、赤パプリカ、黄パプリカ、かぼちゃ、プチトマト、さやえんどうなど', amount: '合わせて400g' },
      { group_label: 'A', name: 'アンチョビ（みじん切り）', amount: '小さじ1（6g）' },
      { group_label: 'A', name: 'スタッフドオリーブ（みじん切り）', amount: '3個' },
      { group_label: 'A', name: 'オリーブ油', amount: '大さじ1' },
      { group_label: 'A', name: '白ワインビネガー', amount: '小さじ2' },
      { group_label: 'A', name: 'レモン汁', amount: '小さじ1' },
      { group_label: 'A', name: '塩、こしょう', amount: '各少々' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      'キャベツ、赤キャベツは芯を残したままくし形に切り、その他の野菜はひとくち大または薄めに切っておく。',
      '黒皿に2を広げてのせる。',
      '3を上段に入れ、過熱水蒸気 36焼き野菜で焼く。',
      '加熱後皿に盛り、合わせたAを添える。',
    ],
  },
  {
    id: 25, title: '野菜の肉巻き', subtitle: '', category_id: 4, auto_menu_id: 36,
    servings: '4人分', heating_time: '仕上がり調節強で約26分',
    heating_method: '過熱水蒸気・グリル 36焼き野菜（仕上がり調節強）', temperature: '',
    tips: '巻き終わりを下にして黒皿の中央に寄せて並べる。',
    notes: '給水タンクに満水ラインまで水を入れてセットする。',
    ingredients: [
      { group_label: '', name: '豚バラ薄切り肉（しゃぶしゃぶ用）', amount: '300g' },
      { group_label: '', name: 'かぼちゃ、赤パプリカ、黄パプリカ、ヤーコン、オクラ、水菜、アスパラガス、えのきだけ、山いもなど', amount: '合わせて約250g' },
      { group_label: '', name: '塩、こしょう', amount: '各少々' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      '各野菜を5cm長さの棒状に切り、肉は巻きやすく広げる。',
      '広げた肉を2のそれぞれの野菜に端から巻きつけ塩、こしょうをふっておく。',
      '3の巻き終わりを下にして黒皿の中央に寄せて並べ、上段に入れ 過熱水蒸気 36焼き野菜 仕上がり調節強で焼く。',
    ],
  },
  {
    id: 26, title: 'ローストビーフ', subtitle: '', category_id: 4, auto_menu_id: null,
    servings: '5〜6人分', heating_time: '50〜60分',
    heating_method: 'オーブン（予熱なし）210℃', temperature: '210℃（予熱なし）',
    tips: '十分冷ましてからたこ糸を取って薄く切る。グレービーソース：黒皿に残った野菜と肉汁を鍋に移し、スープを加えて煮つめ、ふきんでこし塩こしょうをして作る。',
    notes: '',
    ingredients: [
      { group_label: '', name: '牛もも肉（かたまり）', amount: '約800g' },
      { group_label: '', name: 'にんにく（すりおろす）', amount: '1片' },
      { group_label: '', name: 'にんじん、玉ねぎ、セロリ（約1cm幅に切る）', amount: '各50g' },
      { group_label: '', name: '塩、こしょう', amount: '各少々' },
      { group_label: '', name: 'サラダ油', amount: '小さじ1/2' },
    ],
    steps: [
      '牛肉に塩、こしょうをし、にんにくをすり込み、木綿製のたこ糸でしばって形を整え、サラダ油を全体に塗る。',
      '黒皿の中央に寄せて野菜を広げ、上に1をのせ下段に入れ オーブン 予熱なし 210℃ 50〜60分で焼く。',
      '十分冷ましてからたこ糸を取って薄く切り、お好みの野菜（分量外）とともに器に盛り、グレービーソースを添える。',
    ],
  },
  {
    id: 27, title: '焼きとり', subtitle: '', category_id: 4, auto_menu_id: null,
    servings: '12くし分（3〜4人分）', heating_time: '17〜22分 裏返して6〜11分',
    heating_method: 'グリル', temperature: '',
    tips: '黒皿の汚れが気になるときはオーブンシートを敷く。',
    notes: '合わせたBの中にAをつけ込み、30分〜1時間おいて肉と野菜を交互に竹ぐしに刺す。',
    ingredients: [
      { group_label: '', name: '鶏もも肉（皮つき、ひとくち大に切る）', amount: '2枚' },
      { group_label: 'A', name: '長ねぎ（4〜5cm長さに切る）', amount: '2本' },
      { group_label: 'A', name: 'ししとうがらし（種を取る）', amount: '12本' },
      { group_label: 'B', name: 'しょうゆ', amount: 'カップ1/2' },
      { group_label: 'B', name: 'みりん', amount: 'カップ1/4' },
      { group_label: 'B', name: '砂糖', amount: '大さじ2〜3' },
      { group_label: 'B', name: 'サラダ油', amount: '大さじ1' },
    ],
    steps: [
      '合わせたBの中にAをつけ込み、ときどき返しながら、30分〜1時間おいて、肉と野菜を交互に竹ぐしに刺しておく。',
      '1を黒皿に並べ、上段に入れ グリル 17〜22分で焼き、裏返して グリル 6〜11分で焼く。',
    ],
  },
  {
    id: 28, title: '鶏の照り焼き', subtitle: '', category_id: 4, auto_menu_id: null,
    servings: '4人分', heating_time: '23〜27分',
    heating_method: 'オーブン（予熱なし）200℃', temperature: '200℃（予熱なし）',
    tips: '1回に焼ける分量は1〜2枚分。',
    notes: '30分〜1時間以上つけて下味をつける。',
    ingredients: [
      { group_label: '', name: '鶏むね肉またはもも肉（皮つき、1枚約250gの物）', amount: '2枚' },
      { group_label: 'A', name: 'しょうゆ', amount: '大さじ2' },
      { group_label: 'A', name: 'みりん', amount: '大さじ1' },
      { group_label: 'A', name: '砂糖', amount: '小さじ1' },
      { group_label: 'A', name: 'しょうが汁', amount: '少々' },
    ],
    steps: [
      '鶏肉は、皮をフォークなどで穴をあけ、厚みのあるところは切り目を入れて合わせたAに30分〜1時間ほどつけて下味をつけ、汁けをかるく切る。',
      '1の皮を上にして黒皿の中央に寄せて並べ、上段に入れ、オーブン 予熱なし 200℃ 23〜27分で焼く。',
    ],
  },
  // ===== 揚げ物（油なし）=====
  {
    id: 29, title: '鶏のから揚げ', subtitle: '油なし', category_id: 5, auto_menu_id: 37,
    servings: '12個分', heating_time: '約24分',
    heating_method: '過熱水蒸気・グリル 37鶏のから揚げ', temperature: '',
    tips: '片栗粉の量は油を使わないので少量にする。たくさんまぶすと粉が残る。骨つきの鶏肉は仕上がり調節強にする。市販のから揚げ粉を使うと便利。',
    notes: '給水タンクに満水ラインまで水を入れてセットする。',
    ingredients: [
      { group_label: '', name: '鶏もも肉（皮つき、1枚約250gの物）', amount: '2枚' },
      { group_label: 'A', name: 'しょうゆ', amount: '大さじ2' },
      { group_label: 'A', name: '酒', amount: '大さじ1 1/2' },
      { group_label: 'A', name: 'しょうが（すりおろす）', amount: '小さじ1 1/2' },
      { group_label: 'A', name: 'にんにく（すりおろす）', amount: '小さじ1 1/2' },
      { group_label: 'A', name: 'こしょう', amount: '少々' },
      { group_label: '', name: '片栗粉', amount: '大さじ1' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      '鶏肉は1枚を6等分してAにつけ込み、15分以上おく。',
      '2の汁けをかるく切っておき、ポリ袋（市販）に片栗粉を入れ、そこへ鶏肉を加えてもみ込むようにしてまぶす。',
      '黒皿に、3の鶏肉をポリ袋から取り出して、余分な片栗粉をたたいて落とし、皮を上にして中央に寄せて並べ、上段に入れ 過熱水蒸気 37鶏のから揚げで加熱する。',
    ],
  },
  {
    id: 30, title: 'オーブン天ぷら', subtitle: '油なし', category_id: 5, auto_menu_id: 38,
    servings: '12個分', heating_time: '約28分',
    heating_method: '過熱水蒸気・グリル 38オーブン天ぷら', temperature: '',
    tips: '油は使わず衣は天かすを使う。材料はきすのかわりにえび、いか、あなごなどの魚介類でもできる。材料の大きさ、厚さをそろえる。かぼちゃやさつまいもなどは5mmくらいの厚さに切る。',
    notes: '給水タンクに満水ラインまで水を入れてセットする。',
    ingredients: [
      { group_label: '', name: 'きす（開いた物）', amount: '4枚（約100g）' },
      { group_label: '', name: 'かぼちゃ、さつまいも、れんこんの薄切り', amount: '各2枚（約150g）' },
      { group_label: '', name: '小麦粉（薄力粉）', amount: '大さじ1強' },
      { group_label: '', name: '卵（溶きほぐす）', amount: '1/2個' },
      { group_label: '', name: '天かす', amount: '約60g' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      '天かすをビニール袋に入れ、めん棒で細かく砕いて容器に入れる。',
      '水けを切ったきす、野菜に小麦粉、卵、2の順につける。',
      '黒皿にアルミホイルまたはオーブンシートを敷き、きすは皮を上にして、それぞれ中央に寄せて並べ、上段に入れ 過熱水蒸気 38オーブン天ぷらで加熱する。',
    ],
  },
  {
    id: 31, title: 'ヒレカツ', subtitle: '油なし', category_id: 5, auto_menu_id: 39,
    servings: '12個分（3枚分）', heating_time: '約25分',
    heating_method: '過熱水蒸気・グリル 39ヒレカツ', temperature: '',
    tips: '油は使わず衣は煎りパン粉（フライパンで焦がさないように煎ったもの）を使う。1回に焼ける分量は表示の分量の0.8〜1.3倍量。',
    notes: '給水タンクに満水ラインまで水を入れてセットする。',
    ingredients: [
      { group_label: '', name: '豚ヒレ肉（かたまり）', amount: '300g' },
      { group_label: '', name: '塩、こしょう', amount: '各少々' },
      { group_label: '', name: '煎りパン粉', amount: '50g' },
      { group_label: '', name: '小麦粉（薄力粉）', amount: '大さじ2' },
      { group_label: '', name: '卵（溶きほぐす）', amount: '1個' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      '豚ヒレ肉は12等分に切り、塩、こしょうをする。',
      '2に小麦粉、卵、煎りパン粉の順につける。',
      '黒皿にアルミホイルまたはオーブンシートを敷き、3を中央に寄せて並べ、上段に入れ 過熱水蒸気 39ヒレカツで加熱する。',
    ],
  },
  {
    id: 32, title: 'とんカツ', subtitle: '油なし', category_id: 5, auto_menu_id: 40,
    servings: '3枚分', heating_time: '約22分',
    heating_method: '過熱水蒸気・グリル 40とんカツ', temperature: '',
    tips: '煎りパン粉（フライパンで焦がさないように煎ったもの）を使う。',
    notes: '給水タンクに満水ラインまで水を入れてセットする。',
    ingredients: [
      { group_label: '', name: '豚ロース肉（1枚約100gの物）', amount: '3枚' },
      { group_label: '', name: '塩、こしょう', amount: '各少々' },
      { group_label: '', name: '小麦粉（薄力粉）', amount: '大さじ2' },
      { group_label: '', name: '卵（溶きほぐす）', amount: '1個' },
      { group_label: '', name: '煎りパン粉', amount: '50g' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      '豚ロース肉に塩、こしょうをする。',
      '2に小麦粉、卵、煎りパン粉の順につける。',
      '黒皿にアルミホイルまたはオーブンシートを敷き、3を中央に寄せて並べ、上段に入れ 過熱水蒸気 40とんカツで加熱する。',
    ],
  },
  {
    id: 33, title: 'チキンカツ', subtitle: '油なし', category_id: 5, auto_menu_id: 41,
    servings: '12個分', heating_time: '約22分',
    heating_method: '過熱水蒸気・グリル 41チキンカツ', temperature: '',
    tips: '煎りパン粉を使う。',
    notes: '給水タンクに満水ラインまで水を入れてセットする。',
    ingredients: [
      { group_label: '', name: '鶏ささみ', amount: '4本' },
      { group_label: '', name: '塩、こしょう', amount: '各少々' },
      { group_label: '', name: '小麦粉（薄力粉）', amount: '大さじ2強' },
      { group_label: '', name: '卵（溶きほぐす）', amount: '1個' },
      { group_label: '', name: '煎りパン粉', amount: '60g' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      '鶏ささみは3等分にし、塩、こしょうをする。',
      '2に小麦粉、卵、煎りパン粉の順につける。',
      '黒皿にアルミホイルまたはオーブンシートを敷き、3を中央に寄せて並べ、上段に入れ 過熱水蒸気 41チキンカツで加熱する。',
    ],
  },
  {
    id: 34, title: 'えびフライ', subtitle: '油なし', category_id: 5, auto_menu_id: 42,
    servings: '12本分', heating_time: '約22分',
    heating_method: '過熱水蒸気・グリル 42えびフライ', temperature: '',
    tips: '煎りパン粉を使う。',
    notes: '給水タンクに満水ラインまで水を入れてセットする。',
    ingredients: [
      { group_label: '', name: '大正えび（またはブラックタイガー）', amount: '12尾' },
      { group_label: '', name: '小麦粉（薄力粉）', amount: '大さじ2' },
      { group_label: '', name: '卵（溶きほぐす）', amount: '1個' },
      { group_label: '', name: '塩、こしょう', amount: '各少々' },
      { group_label: 'A', name: '煎りパン粉', amount: '60g' },
      { group_label: 'A', name: 'パセリ（みじん切り）', amount: '少々' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      'えびは尾と一節を残して殻をむき、背わたを取る。Aは合わせておく。',
      'えびに塩、こしょうをし、小麦粉、卵、Aの順につける。',
      '黒皿にアルミホイルまたはオーブンシートを敷き、3を中央に寄せて並べ、上段に入れ 過熱水蒸気 42えびフライで加熱する。',
    ],
  },
  // ===== 煮物 =====
  {
    id: 35, title: '肉じゃが', subtitle: '', category_id: 6, auto_menu_id: 9,
    servings: '4人分', heating_time: '約60分',
    heating_method: 'レンジ・飲み物デイリー 9肉じゃが', temperature: '',
    tips: '容器は大きくて深めの物を使いふきこぼれないようにする。煮汁は材料がかぶるくらいの量にする。落としぶたをする（オーブンシートを丸形に切り十文字の切り目を入れる）。',
    notes: '',
    ingredients: [
      { group_label: '', name: '豚バラ薄切り肉（ひとくち大に切る）', amount: '150g' },
      { group_label: '', name: 'じゃがいも（乱切りにして水にさらす）', amount: '中1個（約300g）' },
      { group_label: '', name: 'にんじん（乱切り）', amount: '小1本（約100g）' },
      { group_label: '', name: '玉ねぎ（くし形切り）', amount: '小1個（約100g）' },
      { group_label: '', name: '干ししいたけ（戻して石づきを取り、半分に切る）', amount: '6枚' },
      { group_label: 'A', name: 'だし汁', amount: 'カップ1 1/2' },
      { group_label: 'A', name: 'しょうゆ', amount: '大さじ4' },
      { group_label: 'A', name: '酒', amount: 'カップ1/2' },
      { group_label: 'A', name: '砂糖', amount: '大さじ4' },
      { group_label: '', name: 'サラダ油', amount: '適量' },
      { group_label: '', name: 'さやえんどう（ゆでた物）', amount: '適量' },
    ],
    steps: [
      'フライパンにサラダ油を熱し、豚肉をいためる。',
      '容器に1と野菜、合わせたAを入れ、落としぶたをしてふたをする。',
      '飲み物・デイリー 9肉じゃがで加熱する（加熱途中1〜2度かき混ぜる）。',
      '器に盛り、さやえんどうを添える。',
    ],
  },
  {
    id: 36, title: 'ポークカレー', subtitle: '', category_id: 6, auto_menu_id: 9,
    servings: '4人分', heating_time: '約40分（下ごしらえ レンジ600W 4分〜5分30秒）',
    heating_method: 'レンジ・飲み物デイリー 9肉じゃが（仕上がり調節弱）', temperature: '',
    tips: '加熱の途中1〜2度かき混ぜる。',
    notes: '',
    ingredients: [
      { group_label: '', name: '豚肉（角切）', amount: '200g' },
      { group_label: '', name: '塩、こしょう', amount: '各少々' },
      { group_label: 'A', name: 'じゃがいも（乱切りにして水にさらす）', amount: '大1個（約200g）' },
      { group_label: 'A', name: '玉ねぎ（くし形切り）', amount: '中1個（約200g）' },
      { group_label: 'A', name: 'にんじん（乱切り）', amount: '小1本（約100g）' },
      { group_label: 'B', name: 'カレールー', amount: '小1箱（約120g）' },
      { group_label: 'B', name: '水', amount: 'カップ2 1/2〜3' },
      { group_label: '', name: 'サラダ油', amount: '適量' },
    ],
    steps: [
      '豚肉に塩、こしょうをし、フライパンにサラダ油を熱し、手早くいためて取り出し、Aを入れて十分いためる。',
      '容器にBを入れて、ふたをする。レンジ600W 4分〜5分30秒で加熱し、よくかき混ぜてルーを溶かす。',
      '2に1を加えてよくかき混ぜ、ふたをして 飲み物・デイリー 9肉じゃが 仕上がり調節弱で加熱する（途中1〜2度かき混ぜる）。',
    ],
  },
  {
    id: 37, title: '大根といかの煮付け', subtitle: '', category_id: 6, auto_menu_id: 9,
    servings: '4人分', heating_time: '約55分（下ごしらえ 7根菜 仕上がり調節弱）',
    heating_method: 'レンジ・飲み物デイリー 9肉じゃが（仕上がり調節やや弱）', temperature: '',
    tips: '大根は面取りをして裏に十文字のかくし包丁を入れてから下ゆで（7根菜）する。落としぶたをする。',
    notes: '',
    ingredients: [
      { group_label: '', name: '大根', amount: '適量（約500g）' },
      { group_label: '', name: 'いか', amount: '適量' },
      { group_label: 'A', name: 'しょうゆ', amount: '大さじ3' },
      { group_label: 'A', name: '砂糖', amount: '大さじ2' },
      { group_label: 'A', name: 'みりん', amount: '大さじ2' },
      { group_label: 'A', name: 'だし汁', amount: 'カップ1 1/2' },
    ],
    steps: [
      '大根は2cm厚さの輪切りか、大きい物は半月切りにし、面取りをして裏に十文字のかくし包丁を入れ、ラップで包み 7根菜 仕上がり調節弱で加熱する。',
      '容器に1といかを入れ、合わせたAを加えてかき混ぜ、オーブンシートで落としぶたとふたをして 飲み物・デイリー 9肉じゃが 仕上がり調節やや弱で加熱する。',
    ],
  },
  {
    id: 38, title: '里いもの含め煮', subtitle: '', category_id: 6, auto_menu_id: 9,
    servings: '4人分', heating_time: '約55分',
    heating_method: 'レンジ・飲み物デイリー 9肉じゃが（仕上がり調節やや弱）', temperature: '',
    tips: '加熱後、約20分おいて味をしみ込ませる。',
    notes: '',
    ingredients: [
      { group_label: '', name: '里いも（皮をむき、ひとくち大に切る）', amount: '500g' },
      { group_label: 'A', name: 'だし汁', amount: 'カップ1' },
      { group_label: 'A', name: 'しょうゆ', amount: '大さじ1' },
      { group_label: 'A', name: '砂糖', amount: '大さじ1' },
      { group_label: '', name: '木の芽', amount: '適量' },
    ],
    steps: [
      '里いもとAを容器に入れ、オーブンシートで落としぶたとふたをして、飲み物・デイリー 9肉じゃが 仕上がり調節やや弱で加熱する。',
      '加熱後、約20分おいて味をしみ込ませる。',
      '器に盛り、木の芽を添える。',
    ],
  },
  {
    id: 39, title: 'かぼちゃの含め煮', subtitle: '', category_id: 6, auto_menu_id: 9,
    servings: '4人分', heating_time: '約55分',
    heating_method: 'レンジ・飲み物デイリー 9肉じゃが（仕上がり調節やや弱）', temperature: '',
    tips: '加熱後、約20分おいて味をしみ込ませる。',
    notes: '',
    ingredients: [
      { group_label: '', name: 'かぼちゃ（ひとくち大に切る）', amount: '500g' },
      { group_label: 'A', name: 'だし汁', amount: 'カップ1' },
      { group_label: 'A', name: 'しょうゆ', amount: '大さじ1' },
      { group_label: 'A', name: '砂糖', amount: '大さじ1' },
    ],
    steps: [
      'かぼちゃとAを容器に入れ、オーブンシートで落としぶた（9肉じゃが のコツ参照）とふたをして、飲み物・デイリー 9肉じゃが 仕上がり調節やや弱で加熱する。',
      '加熱後、約20分おいて味をしみ込ませる。',
    ],
  },
  {
    id: 40, title: '切り干し大根の煮物', subtitle: '', category_id: 6, auto_menu_id: 9,
    servings: '4人分', heating_time: '約40分',
    heating_method: 'レンジ・飲み物デイリー 9肉じゃが（仕上がり調節弱）', temperature: '',
    tips: '落としぶたをする。',
    notes: '切り干し大根は水で約30分つけて戻す。',
    ingredients: [
      { group_label: '', name: '切り干し大根', amount: '40g' },
      { group_label: '', name: '油揚げ', amount: '2枚' },
      { group_label: '', name: '干ししいたけ（戻して石づきを取り、薄切り）', amount: '2枚' },
      { group_label: '', name: 'にんじん（3cmの長さにせん切り）', amount: '1/2本' },
      { group_label: 'A', name: 'だし汁', amount: 'カップ3' },
      { group_label: 'A', name: '砂糖', amount: '小さじ2' },
      { group_label: 'A', name: '酒', amount: '大さじ1' },
      { group_label: 'A', name: 'しょうゆ', amount: '大さじ2' },
      { group_label: 'A', name: 'みりん', amount: '大さじ1' },
      { group_label: 'A', name: 'ごま油', amount: '小さじ2' },
    ],
    steps: [
      '切り干し大根は水洗いしてから水で約30分つけて戻し、水けを絞ってざく切りにする。油揚げは湯通しし、ヨコ半分に切って細切りにする。',
      '容器に1と残りの材料、合わせたAを入れよく混ぜて落としぶたとふたをして 飲み物・デイリー 9肉じゃが 仕上がり調節弱で加熱する。',
    ],
  },
  // ===== ピザ・グラタン =====
  {
    id: 41, title: 'ピザ', subtitle: '手作りピザ生地', category_id: 8, auto_menu_id: 13,
    servings: '直径24cmのピザ1枚分', heating_time: '予熱あり',
    heating_method: 'オーブン・飲み物デイリー 13ピザ（予熱あり）', temperature: '予熱あり',
    tips: '焼く前に冷めてしまったら レンジ500W で人肌くらい（約40℃）にあたためてから焼く。具の状態によって焼き色が違うので注意。',
    notes: '一次発酵：スチームレンジ発酵で約10分。',
    ingredients: [
      { group_label: 'A', name: '小麦粉（強力粉）', amount: '100g' },
      { group_label: 'A', name: '小麦粉（薄力粉）', amount: '50g' },
      { group_label: 'A', name: '砂糖', amount: '10g' },
      { group_label: 'A', name: '塩', amount: '2g' },
      { group_label: 'B', name: '水', amount: '10mL' },
      { group_label: 'B', name: 'オリーブ油', amount: '15mL' },
      { group_label: '', name: 'ドライイースト（顆粒状で予備発酵不要の物）', amount: '2g' },
      { group_label: '', name: 'ピザソース（市販の物）', amount: '適量' },
      { group_label: 'C', name: '玉ねぎ（薄切り）', amount: '大1/4個（約75g）' },
      { group_label: 'C', name: 'ベーコン（たんざく切り）', amount: '50g' },
      { group_label: 'C', name: 'サラミソーセージ（薄切り）', amount: '8枚' },
      { group_label: 'C', name: 'ピーマン（輪切り）', amount: '2個' },
      { group_label: 'C', name: 'マッシュルーム（缶詰、薄切り）', amount: '小1/2缶（約13g）' },
      { group_label: '', name: '塩、こしょう', amount: '各少々' },
      { group_label: '', name: 'スタッフドオリーブ（薄切り）', amount: '4個' },
      { group_label: '', name: 'ナチュラルチーズ（細かくきざんだ物）', amount: '100g' },
    ],
    steps: [
      'AとドライイーストをふるいにかけてBを加え、手でかるく混ぜてひとまとめにし、よくこねる。',
      '生地をバターを薄く塗ったボウルに入れ、黒皿にのせて下段に入れ スチームレンジ発酵 仕上がり調節中 約10分で一次発酵させる。',
      'のし台で袋から取り出し、生地をかるく押して中のガスを抜き、直径24cmくらいの円形にのばして、オーブンシートを敷いた黒皿にのせる。',
      'のばした生地にフォークで穴をあけ、ピザソースを塗り、Cを並べてかるく塩、こしょうをし、チーズとオリーブを全体に散らす。',
      '食品を入れずに 飲み物・デイリー 13ピザで予熱する。',
      '予熱終了音が鳴ったら、4を下段に入れて焼く。',
    ],
  },
  // ===== 自家製食品 =====
  {
    id: 42, title: '手作りソーセージ', subtitle: '', category_id: 9, auto_menu_id: 32,
    servings: '2本分', heating_time: '仕上がり調節やや弱で約60分',
    heating_method: 'スチーム調理 32自家製食品（仕上がり調節やや弱）', temperature: '',
    tips: '',
    notes: '給水タンクに満水ラインまで水を入れてセットする。',
    ingredients: [
      { group_label: '', name: '豚ももひき肉', amount: '400g' },
      { group_label: '', name: '玉ねぎ（すりおろす）', amount: '大さじ1' },
      { group_label: '', name: 'にんにく（すりおろす）', amount: '小さじ1' },
      { group_label: '', name: '牛乳', amount: '大さじ3' },
      { group_label: '', name: '片栗粉', amount: '大さじ2' },
      { group_label: '', name: '塩', amount: '小さじ1' },
      { group_label: '', name: 'こしょう、ナツメグ、パプリカ、クローブ、タイムなど', amount: '各少々' },
      { group_label: '', name: 'サラダ油', amount: '少々' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      '材料全部を合わせてよくねり混ぜ、2等分して、手にサラダ油をつけて空気を抜き、なめらかにする。',
      '生地をそれぞれ直径4cmくらいの棒状にしてオーブンシートで巻き寿司の要領で巻き、両端をねじる。',
      '3を黒皿にのせ、上段に入れ スチーム調理 32自家製食品で加熱する。',
    ],
  },
  {
    id: 43, title: 'ベーコンと玉ねぎのキッシュ', subtitle: '', category_id: 9, auto_menu_id: null,
    servings: '直径21cmの耐熱焼き皿1皿分', heating_time: '25〜30分',
    heating_method: 'オーブン（予熱なし）210℃', temperature: '210℃（予熱なし）',
    tips: '黒皿の傷が気になるときはオーブンシートを敷く。',
    notes: '',
    ingredients: [
      { group_label: '', name: 'ベーコン', amount: '適量' },
      { group_label: '', name: '玉ねぎ', amount: '適量' },
      { group_label: '', name: 'にんにく（みじん切り）', amount: '少々' },
      { group_label: '', name: 'バター', amount: '適量' },
      { group_label: '', name: '卵（溶きほぐす）', amount: '2個' },
      { group_label: 'A', name: 'スープ（固形スープの素1/4個を溶く）', amount: '30mL' },
      { group_label: 'A', name: '塩、こしょう', amount: '各少々' },
      { group_label: '', name: 'ナチュラルチーズ（細かくきざんだ物）', amount: '60g' },
    ],
    steps: [
      'フライパンにバターを熱し、にんにくをいため、ベーコンと玉ねぎを加えてさらにいため、塩、こしょうをする。',
      'ボウルに卵と合わせたAを入れてよくかき混ぜ、裏ごしする。',
      '2に1とチーズ2/3量を加えて混ぜ、薄くバター（分量外）を塗った焼き皿に流し入れ、上に残りのチーズをふる。',
      '3を黒皿に並べ、下段に入れ オーブン 予熱なし 210℃ 25〜30分で焼く。',
    ],
  },
  // ===== パン =====
  {
    id: 44, title: 'バターロール（ロールパン）', subtitle: '', category_id: 10, auto_menu_id: null,
    servings: '9個分', heating_time: '予熱あり 16〜22分（発酵 一次：50〜60分、二次：25〜40分）',
    heating_method: 'スチームオーブン発酵40℃ + オーブン（予熱あり）170℃', temperature: '170℃（予熱あり）',
    tips: '生地のひとつひとつを表面がなめらかになるように丸める。三角形の底辺からクルクルと巻く。',
    notes: '給水タンクに満水ラインまで水を入れてセットする。',
    ingredients: [
      { group_label: 'A', name: '小麦粉（強力粉）', amount: '200g' },
      { group_label: 'A', name: '砂糖', amount: '大さじ2 1/2' },
      { group_label: 'A', name: '塩', amount: '小さじ1/2（約3g）' },
      { group_label: '', name: 'ドライイースト（顆粒状で予備発酵不要の物）', amount: '小さじ1（約2.5g）' },
      { group_label: 'B', name: 'ぬるま湯（約40℃）', amount: '20〜40mL' },
      { group_label: 'B', name: '卵（溶きほぐす）', amount: '1/2個（約25mL）' },
      { group_label: 'B', name: '牛乳（室温に戻す）', amount: '70mL' },
      { group_label: '', name: 'バター（室温に戻す）', amount: '30g' },
      { group_label: 'つやだし用', name: '卵（溶きほぐす）', amount: '1/2個' },
      { group_label: 'つやだし用', name: '塩', amount: '小さじ1/4' },
    ],
    steps: [
      '給水タンクに満水ラインまで水を入れてセットする。',
      'ボウルにAとドライイーストをふるい入れ、Bを加えて手でかるく混ぜ、バターを少しずつ加え、よく混ぜてひとまとめにする。',
      '生地がベトつかなくなるまでよくこね、約15分こねて生地を丸める。',
      'バター（分量外）を薄く塗ったボウルに4を入れ、黒皿にのせて下段に入れ スチームオーブン発酵 40℃ 50〜60分で一次発酵させる。',
      'ボウルをふせて生地を取り出し、手でかるく押して中のガスを抜く。',
      '生地を9個に切り分け、丸めて約20分休ませる（ベンチタイム）。',
      '生地を円すい形にし、さらにめん棒で細長い三角形にのばし、三角形の底辺からクルクルと巻く。',
      'オーブンシートを敷いた黒皿に巻き終わりを下にして並べ、下段に入れ スチームオーブン発酵 40℃ 25〜40分で二次発酵させる。',
      '表面につやだし用卵を薄く塗る。食品を入れずに オーブン 予熱あり 170℃ 16〜22分で予熱する。',
      '予熱終了音が鳴ったら9を下段に入れて焼く。',
    ],
  },
  {
    id: 45, title: 'アップルパイ', subtitle: '', category_id: 11, auto_menu_id: null,
    servings: '直径21cmのパイ1個分', heating_time: '予熱あり 36〜42分',
    heating_method: 'オーブン（予熱あり）190℃', temperature: '190℃（予熱あり）',
    tips: '型は金属製の物を使う（耐熱ガラス製の型では上手に焼けないことがある）。生地が扱いにくいときは冷蔵室で20〜30分休ませると作りやすくなる。冷凍パイシートを使うと便利（1枚・約100gの物を4枚）。',
    notes: '',
    ingredients: [
      { group_label: '', name: '小麦粉（強力粉）', amount: '100g' },
      { group_label: '', name: '小麦粉（薄力粉）', amount: '100g' },
      { group_label: '', name: 'バター（2cm角に切り、冷たい物）', amount: '140g' },
      { group_label: '', name: '冷水', amount: '90〜110mL' },
      { group_label: 'りんごのプリザーブ', name: 'りんご（紅玉またはふじ）', amount: '2個' },
      { group_label: 'りんごのプリザーブ', name: '砂糖', amount: '100g' },
      { group_label: 'りんごのプリザーブ', name: 'レモン汁', amount: '大さじ1' },
      { group_label: 'りんごのプリザーブ', name: 'シナモン', amount: '少々' },
      { group_label: 'つやだし用', name: '卵（溶きほぐす）', amount: '1/2個' },
      { group_label: 'つやだし用', name: '塩', amount: '小さじ1/4' },
    ],
    steps: [
      '【りんごのプリザーブ】りんごはタテ4つ割りにして5mm厚さのいちょう切りにし、塩水につけてからかるく水洗いをして、水けを切る。',
      '大きめの耐熱容器に1とAを入れてかき混ぜ レンジ600W 7〜9分加熱する。アクを取って混ぜ、再び レンジ600W 5〜7分加熱する。シナモンを加えて混ぜ、冷めてからざるに上げて汁けを切る。',
      '【パイ生地】バター以外の粉類を合わせ、バターを加えてポロポロ状にし、冷水を少しずつ加えてひとまとめにする。ラップで包み冷蔵室で約1時間休ませる。',
      '生地を3mm厚さに伸ばし、パイ皿に敷いてフォークで穴を開ける。りんごのプリザーブを詰め、テープ状に切った生地を組んで上面を覆い、端を貼りつける。つやだし用卵を塗る。',
      '食品を入れずに オーブン 予熱あり 190℃ 36〜42分で予熱する。',
      '予熱終了音が鳴ったら4を下段に入れて焼く。',
    ],
  },
];

module.exports = { categories, autoMenus, recipes };
